FROM eclipse-mosquitto

#Maintainer
MAINTAINER onesait things edge <fgminambre@minsait.com>

#Let's start
RUN apk add logrotate

COPY conf/mosquitto.conf /mosquitto/config/
COPY conf/mosquitto_log_conf  /etc/logrotate.d/

EXPOSE 1883
