FROM woahbase/alpine-mosquitto:armhf

#Maintainer
MAINTAINER onesait things edge <fgminambre@minsait.com>

#Let's start
RUN  mkdir -p /mosquitto/config
COPY ["conf/10-setup", "/root/etc/cont-init.d/"]
COPY ["conf/mosquitto.conf", "/mosquitto/config/"]
COPY ["conf/mosquitto_log_conf",  "/etc/logrotate.d/"]


EXPOSE 1883
ENTRYPOINT ["/init"]
#CMD ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]


